service: reservio-test-v01

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-plugin-typescript
